### ISSUE TITLE
Let's finish the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-alhana-yo#1]
Good job @alhana-yo !!!

Here you have some tips to improve the exercise:

- [x] Define the logic to make the counter work
- [x] Remember to convert input value string to a number
- [ ] Extract the feedback painter to a function
- [ ] Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an `else` statement
- [x] Move variables declaration to the top of the file
- [x] Indent and avoid extra white spaces to improve readability and prevent bugs
- [ ] Remove commented code

Let me know if you have any doubts ;)

Go for it!!

**Comment by oneeyedman** [comment]
Well done @alhana-yo! 

Just improve it a bit by implementing the last three tips ;)
- [ ] Extract the feedback painter to a function
- [ ] Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an else statement
- [ ] Remove commented code

**Comment by alhana-yo** [comment]
> Good job @alhana-yo !!!
> 
> Here you have some tips to improve the exercise:
> 
> * [x]  Define the logic to make the counter work
> * [x]  Remember to convert input value string to a number
> * [ ]  Extract the feedback painter to a function
> * [x]  Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an `else` statement
> * [x]  Move variables declaration to the top of the file
> * [x]  Indent and avoid extra white spaces to improve readability and prevent bugs
> * [x]  Remove commented code
> 
> Let me know if you have any doubts ;)
> 
> Go for it!!
Hi! I have done almost all things you suggested.The only thing I haven done is > * [ ] Extract the feedback painter to a function... I dont know what you mean, because it is already inseide a function XD
Could you please help me with this issue? Thanks!

**Comment by oneeyedman** [comment]
Oki, I want you to create a function to write the clues ;)
